[versions]
mprisJava = "1.0.0-SNAPSHOT" # Project version
dbusJava = "3.3.2"           # dbus-java version
jetbrainsAnnotations = "26.0.2" # Jetbrains annotations version

[libraries]
dbusJava = { module = "com.github.hypfvieh:dbus-java", version.ref = "dbusJava" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }

[plugins]
